"""Pydantic schemas for MCP tool inputs and outputs."""

from fiji_mcp.schemas.tool_outputs import (
    BatchMacroStepFailure,
    BatchMacroStepSuccess,
    CommandEntry,
    DescribePluginResult,
    ExtensionEntry,
    GetImageInfoResult,
    HealthCheckResult,
    ListAllCommandsResult,
    ListExtensionsResult,
    ListOpenImagesResult,
    MacroRunResult,
    OpenImageResult,
    PluginInputMeta,
    RunBatchMacrosResult,
    RunWorkflowResult,
    SaveImageResult,
    ScreenshotResult,
    SearchCommandsResult,
    WorkflowStepFailure,
    WorkflowStepInput,
    WorkflowStepSuccess,
)

__all__ = [
    "BatchMacroStepFailure",
    "BatchMacroStepSuccess",
    "CommandEntry",
    "DescribePluginResult",
    "ExtensionEntry",
    "GetImageInfoResult",
    "HealthCheckResult",
    "ListAllCommandsResult",
    "ListExtensionsResult",
    "ListOpenImagesResult",
    "MacroRunResult",
    "OpenImageResult",
    "PluginInputMeta",
    "RunBatchMacrosResult",
    "RunWorkflowResult",
    "SaveImageResult",
    "ScreenshotResult",
    "SearchCommandsResult",
    "WorkflowStepFailure",
    "WorkflowStepInput",
    "WorkflowStepSuccess",
]
